In [3]:
x = [1, 2, 3]
y = x
print(y)
x[1] = 42
print (y)

[1, 2, 3]
[1, 42, 3]


In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

D:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
mnist = input_data.read_data_sets('MNIST_data/', one_hot = True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [3]:
batch = mnist.train.next_batch(50)
print(batch[1])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.

In [4]:
sess = tf.InteractiveSession()
x = tf.placeholder(tf.float32, shape = [None, 784])
y = tf.placeholder(tf.float32, shape = [None, 10])

In [5]:
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

In [6]:
sess.run(tf.global_variables_initializer())

In [7]:
res = tf.matmul(x,W) + b

In [8]:
pred = tf.nn.softmax(res)
loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(pred), reduction_indices = [1]))
#loss = tf.nn.softmax_cross_entropy_with_logits(labels = y, 
         #                                         logits = pred)

train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)
num_batch = 50
num_epoch = 50
correct_pred = tf.equal(tf.argmax(y,1), tf.argmax(pred,1))
acc = tf.reduce_mean(tf.cast(correct_pred, tf.float32))


In [9]:
for i in range(num_epoch):
    batch = mnist.train.next_batch(50)
    loss_value, acc_value = sess.run([loss, acc], feed_dict = {x: batch[0], 
                               y: batch[1]})
    print('Iteration ' + str(i) + ', loss = ' + str(loss_value) + 
         ', acc = ' + str(acc_value))
    
acc = acc.eval(feed_dict = {x: mnist.test.images,
                           y: mnist.test.labels})
print('The final acc is: {} % '.format(acc))
sess.close()

Iteration 0, loss = 2.3025851, acc = 0.14
Iteration 1, loss = 2.3025851, acc = 0.1
Iteration 2, loss = 2.3025851, acc = 0.1
Iteration 3, loss = 2.3025851, acc = 0.02
Iteration 4, loss = 2.3025851, acc = 0.06
Iteration 5, loss = 2.3025851, acc = 0.1
Iteration 6, loss = 2.3025851, acc = 0.1
Iteration 7, loss = 2.3025851, acc = 0.16
Iteration 8, loss = 2.3025851, acc = 0.06
Iteration 9, loss = 2.3025851, acc = 0.12
Iteration 10, loss = 2.3025851, acc = 0.08
Iteration 11, loss = 2.3025851, acc = 0.16
Iteration 12, loss = 2.3025851, acc = 0.08
Iteration 13, loss = 2.3025851, acc = 0.12
Iteration 14, loss = 2.3025851, acc = 0.04
Iteration 15, loss = 2.3025851, acc = 0.18
Iteration 16, loss = 2.3025851, acc = 0.14
Iteration 17, loss = 2.3025851, acc = 0.1
Iteration 18, loss = 2.3025851, acc = 0.1
Iteration 19, loss = 2.3025851, acc = 0.12
Iteration 20, loss = 2.3025851, acc = 0.08
Iteration 21, loss = 2.3025851, acc = 0.08
Iteration 22, loss = 2.3025851, acc = 0.12
Iteration 23, loss = 2.3025